[package]
name = "hebo"
version = "0.2.7"
authors = ["Xu Shaohua <shaohua@biofan.org>"]
description = "Distributed MQTT broker"
edition = "2021"
categories = [
  "concurrency",
  "network-programming",
]
keywords = [
  "broker",
  "hebo",
  "mqtt",
  "qos",
]
repository = "https://github.com/HeboProject/hebo"
homepage = "https://github.com/HeboProject/hebo"
license = "AGPL-3.0-only"
readme = "./README.md"
publish = true

[[bin]]
name = "hebo"
path = "src/bin/hebo.rs"

[features]
default = []

full = [
  "mongodb_conn",
  "mysql_conn",
  "pgsql_conn",
  "redis_conn",
]
mongodb_conn = ["mongodb"]
mysql_conn = ["mysql_async"]
pgsql_conn = ["tokio-postgres"]
redis_conn = ["redis"]

[dependencies]
base64 = "0.13.1"
chrono = { version = "0.4.22", features = ["serde"] }
clap = "3.2.23"
codec = { path = "../codec", package = "hebo_codec", version = "0.2.2" }
env_logger = "0.9.1"
futures = "0.3.25"
futures-util = "0.3.25"
http = "0.2.8"
jemallocator = { version = "0.5.0", optional = true }
log = "0.4.17"
log4rs = { version = "1.2.0", default-features = true, features = [ "all_components", "background_rotation", "gzip" ] }
mongodb = { version = "2.3.1", optional = true }
mysql_async = { version = "0.30.0", optional = true }
openssl = "0.10.42"
quinn = "0.8.5"
rand = "0.8.5"
redis = { version = "0.21.6", features = ["tokio-comp", "connection-manager"], optional = true }
rustls-pemfile = "1.0.1"
serde = { version = "1.0.147", features = ["derive"] }
tokio = { version = "1.21.2", features = ["full"] }
tokio-postgres = { version = "0.7.7", optional = true }
tokio-rustls = "0.23.4"
tokio-tungstenite = { version = "0.17.2", features = ["rustls"] }
toml = "0.5.9"
users = "0.11.0"
warp = "0.3.3"
webpki-roots = "0.22.5"

[target.'cfg(target_os = "linux")'.dependencies]
nc = "0.8.7"

[dev-dependencies]
rcgen = "0.10.0"
ruo = { path = "../ruo", version = "0.1.2" }
tokio-test = "0.4.2"
