[package]
name = "hebo_codec"
version = "0.2.2"
authors = [
  "Xu Shaohua <shaohua@biofan.org>"
]
description = "Packet codec for MQTT protocol"
categories = [
  "concurrency",
  "network-programming",
]
keywords = [
  "broker",
  "codec",
  "hebo",
  "mqtt",
  "qos",
]
repository = "https://github.com/HeboProject/hebo"
homepage = "https://github.com/HeboProject/hebo/tree/main/codec"
license = "Apache-2.0"
edition = "2021"
readme = "./README.md"
publish = true

[dependencies]
byteorder = "1.4.3"
bytes = "1.2.1"
log = "0.4.17"
rand = "0.8.5"
serde = { version = "1.0.145", features = ["derive"] }
