#!/bin/bash
# Copyright (c) 2022 Xu Shaohua <shaohua@biofan.org>. All rights reserved.
# Use of this source is governed by General Public License that can be found
# in the LICENSE file.

# Install this script into `.git/hooks` directory.

set -xe

cargo clippy --all-targets --all-features --fix --allow-dirty --allow-staged -- \
  --deny warnings \
  --deny clippy::all \
  --deny clippy::cargo \
  --deny clippy::nursery \
  --deny clippy::pedantic

cargo fmt --all

